[package]
name = "dcmpipe_dict_builder"
version = "0.1.0"
authors = ["neandrake <die.drachen@gmail.com>"]
edition = "2018"

[dependencies]
phf_codegen = "0.9"
quick-xml = "0.22"

[lib]
name="dcmpipe_dict_builder"
path="src/lib.rs"
